Register endpoint with Prisma integration test setup
dyazdani/trac pull request #51
Opened 2023-12-23 07:08 UTC by dyazdani

Closes #3 #11 

Tests can fail:
![Screen Shot 2023-12-22 at 23 03 50](https://github.com/dyazdani/trac/assets/99094815/8bf9bf2f-5beb-43dd-bac5-17d03cf573a5)

Passing tests:
![Screen Shot 2023-12-22 at 22 57 59](https://github.com/dyazdani/trac/assets/99094815/d357a8e3-7a7d-4cfa-8963-cbd17792f4c3)

NOTE: There is one test commented out because I could not figure out why it did not pass. It was for the test case of a username in `req.body` that already exists in db.

2023-12-23 19:57 UTC, jvaneyken commented on src/server/api/auth.ts
I feel like this validation is already being handled by the database? We have not null constraints on email, username, and password and unique constraints on email and username. 

https://www.prisma.io/docs/orm/reference/error-reference
https://www.prisma.io/docs/orm/prisma-client/debugging-and-troubleshooting/handling-exceptions-and-errors

2023-12-23 20:07 UTC, jvaneyken requested changes
Overall Looks pretty good to me. I was not able to independently verify that tests were working. There is something I need to set up with docker I think to run the tests. Other than that just blocking because I'm not sure about the user info validation

2023-12-23 20:20 UTC, dyazdani commented on src/server/api/auth.ts
It is handled by the database and the console does log an error, but I added 400 responses because I saw the Prisma guide testing for 400 responses and I felt like a response from the server would provide the client with more information. I guess I could handle the Prisma error to send something to be displayed in the front end. I don't know what's best practice to be honest. At first I tried testing for the Prisma error with Jest, but it wasn't working so that's when I made the 400 responses. If there were a way to use that Prisma error in Jest (which I'm sure there is) and a 400 response is redundant, maybe we make a TODO to change it eventually. What are your thoughts?

2023-12-23 20:39 UTC, dyazdani commented on src/server/api/auth.ts
I just looked at your link. Great find with the error handling guide! I didn't know Prisma would even have that.

2023-12-23 20:43 UTC, jvaneyken commented on src/server/api/auth.ts
Yeah it was totally new to me too. So maybe the answer is that you still send back the 400 responses but use the built in Prisma error codes to handle which message to send back?

2023-12-23 20:45 UTC, dyazdani commented on src/server/api/auth.ts
Yeah, I'll take a look at it. Good idea.

2023-12-27 06:13 UTC, jvaneyken approved these changes

2023-12-27 06:21 UTC, merged